frontend/models.py
from flask_login import UserMixin
from backend.database import db

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True) # primary keys are required by SQLAlchemy
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

frontend/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from backend.database import db
from .models import User

auth_blueprint = Blueprint('auth', __name__, template_folder='templates')

@auth_blueprint.route('/login')
def login():
    return render_template('login.html')

@auth_blueprint.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to the hashed password in database
    if not user or not check_password_hash(user.password, password): 
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('main.client'))

@auth_blueprint.route('/signup')
def signup():
    return render_template('signup.html')

@auth_blueprint.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # create new user with the form data. Hash the password so plaintext version isn't saved.
    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

frontend/main.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from backend.database import db
import requests
import json

main_blueprint = Blueprint('main', __name__, template_folder='templates')

@main_blueprint.route('/')
def index():
    return render_template('index.html')

@main_blueprint.route('/client')
@login_required
def client():
    response = requests.get('http://127.0.0.1:19999/api/client')
    return render_template('client.html', name=current_user.name, clients=json.loads(response.text))
    
@main_blueprint.route('/pos', methods=['POST','GET'])
def pos():
    clientid = request.form.get('clients')
    response = requests.get('http://127.0.0.1:19999/api/pos/' + clientid)
    return render_template('pos.html', poss=json.loads(response.text))

frontend/views.py
from flask import Blueprint, render_template, abort
from jinja2 import TemplateNotFound

frontend_page = Blueprint('simple_page', __name__, template_folder='templates')

@frontend_page.route('/')
def index():
    try:
        context = {"user": 'Joe'}
        return render_template('login.html', context=context)
    except TemplateNotFound:
        abort(404)

frontend/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Connex Administration</title>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" /> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <link rel="stylesheet" href="{{ url_for('static', filename='material.css') }}" />
</head>

<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Connex Admin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                {% if current_user.is_authenticated %}
                <a class="nav-link" href="{{ url_for('main.client') }}">Clients</a>
                {% endif %}
            </li>
          </ul>
          <span class="navbar-text">
            {% if current_user.is_authenticated %}
            <a class="nav-link" href="{{ url_for('auth.logout') }}"">Logout</a>
            {% endif %}
            {% if not current_user.is_authenticated %}
            <ul class="nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Options</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{{ url_for('auth.login') }}">Login</a>
                  <a class="dropdown-item" href="{{ url_for('auth.signup') }}">Sign Up</a>
                </div>
              </li>
            </ul>
            {% endif %}
          </span>
        </div>
    </nav>





            <div class="container-lg">
               {% block content %}
               {% endblock %}
            </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

frontend/templates/client.html
{% extends "base.html" %}

{% block content %}
<br />
<div class="container">
  <div class="row">
    <div class="col-sm">
      <form id="calc" method="POST" action="{{ url_for('main.pos') }}">
        <div class="input-group mb-3">
          <select class="form-control" id="clientlist" name="clients">
              <option selected="true" disabled>Choose Client</option>
              {% for client in clients %}
              <option value="{{client["clientid"]}}">{{client["name"]}}</option>
              {% endfor %}
          </select>
        </div>
        <button type="submit" class="btn btn-primary">Location Configuration</button>
      </form>
    </div>
    <div class="col-sm">
      <div class="card">
        <h5 class="card-header">Client Details</h5>
        <div class="card-body">
          <h5 class="card-title">Special title treatment</h5>
          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
          
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

frontend/templates/index.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

frontend/templates/login.html
{% extends "base.html" %}

{% block content %}
<br />
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Your Email" autofocus="">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input name="password" type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="form-group form-check">
                <input name="remember" type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Remember Me</label>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>
{% endblock %}

frontend/templates/pos.html
{% extends "base.html" %}

{% block content %}
<br />
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">POSID</th>
        <th scope="col">POSGUID</th>
        <th scope="col">Name</th>
        <th scope="col">Activation Code</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for pos in poss %}
      <tr>
        <th scope="row">
          <a class="nav-link" data-toggle="collapse" href="#collapseExample-{{pos["posguid"]}}" role="button" aria-expanded="false" aria-controls="collapseExample">{{pos["posid"]}}</a>
        </th>
        <td>{{pos["posguid"]}}</td>
        <td>{{pos["name"]}}</td>
        <td>{{pos["activationcode"]}}</td>
        <td>
          <div class="btn-group btn-group-sm" role="group" aria-label="...">
            <button type="button" class="btn btn-primary btn-sm">REPOLL</button>
            <button type="button" class="btn btn-primary btn-sm">ACTIVATE</button>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="5">
          <div class="collapse" id="collapseExample-{{pos["posguid"]}}">
            <div class="card" style="width: 18rem;">
              <div class="card-header">
                Software
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">{{pos["postype"]["manufacturername"]}}</li>
                <li class="list-group-item">{{pos["postype"]["name"]}}</li>
                <li class="list-group-item">{{pos["postype"]["description"]}}</li>
              </ul>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

frontend/templates/signup.html
{% extends "base.html" %}

{% block content %}
<br />
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Your Email" autofocus="">
            </div>
            <div class="form-group">
                <label for="exampleInputName1">Name</label>
                <input name="name" class="form-control" id="exampleInputName1" aria-describedby="nameHelp" placeholder="Your Name" autofocus="">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>

        <!--
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form> -->
    </div>
</div>
{% endblock %}